name: tunning_sudoku
description: A sudoku library from SynchroGames.
version: 0.1.3
homepage: https://github.com/ArielM24/tuning_sudoku

environment:
  sdk: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
