name: tunning_sudoku
description: A starting point for Dart libraries or applications.
version: 0.1.1
# repository: https://github.com/ArielM24/tuning_sudoku

environment:
  sdk: ^3.0.6

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
